language: python
sudo: false

cache:
  directories:
    - ~/.cache/pip

python:
  - 3.6

install:
  - apt-get -y install git python3 python3-pip screen

script:
  - nosetests --with-coverage

after_success:
  - coveralls
