#!/bin/bash

# Move into the directory with all Pingu-files
cd "$( dirname $0 )"

# Move into the bot directory.
cd $botDir

id=0
while true
do
	# Si hay un proceso abierto lo cerramos
    if (($id != 0))
    then
        screen -ls | grep Pingu | cut -d. -f1 | awk '{print $1}' | xargs kill
    fi
	
	# Guardamos la hora en formato HH
	hora=$(echo 10#$(date) | cut -d ":" -f 1 | cut -d " " -f 4)
	# Si el programa se acaba de arrancar o son las 5 am se clona el github
	if (($hora == 5 || $id == 0))
	then
		cd $botDir
		rm -rf pingueinstein
		git clone https://github.com/azzorini/pingueinstein
		cp $tokenDir $botDir
		cd $botDirpingueinstein
		chmod +x pingueinstein.py
	fi
    
    screen -S Pingu -d -m ~/pingueinstein/pingueinstein.py
    id=$(screen -list Pingu | cut -d. -f1 | awk '{print $1}')
    #id=$(ps aux | grep SCREEN | grep Pingu | awk '{print $2}')

    date
    echo El programa se reiniciará en 10 minutos
    sleep 10m
done
