#!/bin/bash
id=0
while true
do
        # Si hay un proceso abierto lo cerramos
    if (($id != 0))
    then
        screen kill $id
    fi
        
        # Guardamos la hora en formato HH
        hora=$(echo 10#$(date) | cut -d ":" -f 1 | cut -d " " -f 4)
        # Si el programa se acaba de arrancar o son las 5 am se clona el github
        if (($hora == 5 || $id == 0))
        then
                cd /home/bots/files/
                rm -rf pingueinstein
                git clone https://github.com/azzorini/pingueinstein
                cp TOKEN.txt pingueinstein
                grive
                cd pingueistein
                chmod +x pingueinstein.py
    fi
    
    screen -S Pingu -d -m /home/bots/pingueinstein/pingueinstein.py
    id=$(screen -ls | grep Pingu | cut -d '.' -f 1)
    date
    echo El programa se reiniciará en 55 minutos
    sleep 5m
done
