#!/bin/bash

id=0

while true
do

    if (($id != 0))
    then
        screen kill $id
    fi

    screen -S Pingu -d -m ~/Programacion/Python/pingueinstein/pingueinstein.py
    id=$(screen -ls | grep Pingu | cut -d '.' -f 1)

    date
    echo El programa se reiniciará en 4 horas
    sleep 4h
done